// src/routes/project/audio_player/+page.svelte
<script lang="ts">
  import Button from "$lib/components/Button.svelte";
  import Document from "$lib/components/scroll/vertical/Document.svelte";
  import LineText from "$lib/components/LineText.svelte";
  import Header from "$lib/components/Header.svelte";

  let mp3_url = $state<string | null>(null);
  let filename = $state<string | null>(null);

  // the server returns { filename, data } where data is the base64 encoded mp3
  async function fetch_mp3(route: string) {
    try {
      const res = await fetch(`http://0.0.0.0:8000/${route}?t=${Date.now()}`); //diff request to prevent caching
      if (!res.ok) throw new Error('Failed to fetch');
      const json = await res.json();
      filename = json.filename;
      const blob = new Blob([Uint8Array.from(atob(json.data), c => c.charCodeAt(0))], { type: "audio/mpeg" });
      if (mp3_url) URL.revokeObjectURL(mp3_url);
      mp3_url = URL.createObjectURL(blob);
    } catch (error) {
      console.error('Error fetching MP3:', error);
    }
  }
  const next = () => fetch_mp3("nextMp3");
  const previous = () => fetch_mp3("previousMp3");
</script>
<Document>
  <Header/> 
  <LineText>playlist1</LineText>
  <LineText>plays a random song in my definitely-legally-acquired playlist (requires the local server on port 8000).</LineText>
  <LineText>
    <Button on_close={previous}>prev mp3</Button>
    <Button on_close={next}>new mp3</Button>
  </LineText>
  {#if mp3_url}
  <audio autoplay controls src={mp3_url} onended={next}></audio>
  {/if}
  {#if filename}
  <LineText>{filename}</LineText>
  {/if}
</Document>
<style>
  audio {
    display: block;
    width: 100%;
  }
</style>

// src/app/projects/2024/audioPlayer/page.tsx
"use client"
import Navbar from "@/app/components/Nav/Navbar"
// import ThemeWrapper from "@/app/components/ThemeWrapper"
// import Text from "@/app/components/Text/Text"
// import FileSection from "@/app/components/FileSection"
// import TextImageLink from "@/app/components/About/TextImageLink"
import Head from "next/head"
import PageMargin from "@/app/components/PageMargin"
import { useEffect, useRef, useState } from "react";

export default function F(){
    const [mp3Url, setMp3Url] = useState<string | null>(null);
    const [filename, setFilename] = useState<string | null>(null);
    const audioRef = useRef<HTMLAudioElement | null>(null);
    const next = async () => {
        try {
          const res = await fetch(`http://0.0.0.0:8000/nextMp3?t=${Date.now()}`); //diff request to prevent caching
          if (!res.ok) throw new Error('Failed to fetch');

        //   const contentDisposition = res.headers.get('Content-Disposition');
        //   const match = contentDisposition?.match(/filename*="(.+)"/);
        //   const extractedFilename = match?.[1] || 'unknown.mp3';
        //   console.log( contentDisposition);
        //   setFilename(extractedFilename);
    
        //   // Blob response so we can create a URL
        //   const blob = await res.blob();
        //   const url = URL.createObjectURL(blob);
        //   setMp3Url(url);

        const json = await res.json();
        const { filename, data } = json;
        setFilename(filename);

        // Create a Blob URL from base64
        const blob = new Blob([Uint8Array.from(atob(data), c => c.charCodeAt(0))], { type: "audio/mpeg" });
        const url = URL.createObjectURL(blob);
        setMp3Url(url);
        } catch (error) {
          console.error('Error fetching MP3:', error);
        }
      };
    const previous = async () => {
        try {
            const res = await fetch(`http://0.0.0.0:8000/previousMp3?t=${Date.now()}`); //diff request to prevent caching
            if (!res.ok) throw new Error('Failed to fetch');
  
            const json = await res.json();
            const { filename, data } = json;
            setFilename(filename);

            // Create a Blob URL from base64
            const blob = new Blob([Uint8Array.from(atob(data), c => c.charCodeAt(0))], { type: "audio/mpeg" });
            const url = URL.createObjectURL(blob);
            setMp3Url(url);
          } catch (error) {
            console.error('Error fetching MP3:', error);
          }
    }
    // const startStopVideo = () => {
        
    // }
    useEffect(() => {
        const audio = audioRef.current;
        if (!audio) return;
    
        const handleEnded = () => {
            next();
        };

        audio.addEventListener('ended', handleEnded);
        return () => audio.removeEventListener('ended', handleEnded);
      });
     
    return(
        <>
             <Head>
                <title>Playlist1</title>
            </Head>
            <Navbar></Navbar>
            <div className={ " bg-transparent h-max mt-[2rem]"}>

            <center>
                <h1 className=" text-6xl content-center text-c00 w-full">
                    Playlist1
                </h1>
            </center>
            <PageMargin>
                
                <button
                    onClick={previous}
                    className="bg-cblue80 text-c00 px-4 py-2 rounded hover:bg-cbluec0 transition"
                >
                    prev mp3
                </button>
                <button
                    onClick={next}
                    className="bg-cblue80 text-c00 px-4 py-2 rounded hover:bg-cbluec0 transition"
                >
                    new mp3
                </button>
                {mp3Url && (
                    <audio autoPlay ref={audioRef} controls src={mp3Url} className="w-full mt-4" />
                )}
                {filename && (
                    <div className=" text-c00">{filename}</div>
                )}
                {/* <button onClick={startStopVideo()}>Start/Stop</button>
                <button onclick="prevVideo()">PrevAudio</button>
                <button onclick="newVideo()">NewAudio</button>
                <button onclick="(()=>{forwardAudio(-10)})()">-10s</button>
                <button onclick="(()=>{forwardAudio(10)})()">+10s</button>
                <button onclick="(()=>{increaseVolume(-1/16)})()">volume-1/16</button>
                <button onclick="(()=>{increaseVolume(1/16)})()">volume+1/16</button> */}
            </PageMargin>
            </div>
        </>
        
    )
}
